skip_tags: true

os: Visual Studio 2015

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

build_script:
  - "git --no-pager log -n2"
  - "echo %APPVEYOR_REPO_COMMIT%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip install ."
  - "pip install -Ur test-requirements.txt"
  - "pip install codecov"

test_script:
  - "mkdir empty"
  - "cd empty"
  # Make sure it's being imported from where we expect
  - "python -c \"import os, caproto; print(os.path.dirname(caproto.__file__))\""
  # - "coverage run run_tests.py -v --benchmark-disable --timeout=50 --log-format=\"%(asctime)s %(levelname)s (%(threadName)s) %(message)s\" --log-date-format=\"%H:%M:%S,%03d\""
  # - "coverage combine"
  # - "coverage report -m"
